<?php
// generated by Poedit from quote-manager-system-for-woocommerce-el.po, do not edit directly 
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'el','pot-creation-date'=>'2025-04-23 15:19+0300','po-revision-date'=>'2025-04-23 15:19+0300','translation-revision-date'=>'2025-04-23 15:19+0300','project-id-version'=>'Quote Manager System For WooCommerce','x-generator'=>'Poedit 3.6','messages'=>[]];
